name: ros2
on:
  push:
    branches:
      - 'main'
    paths:
      - 'ros2/**/*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/ros2

jobs:
  basecontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./ros2/base
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base
  devcontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - working-directory: ./ros2/devel
        run: |
          set -e

          # Update this based on your image name and the path of the .devcontainer folder in your repository
          IMAGE_REPOSITORY="$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev" | tr '[:upper:]' '[:lower:]')"

          # [Optional] Enable buildkit, set output to plain text for logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Do the build - update
          npm install -g "@vscode/dev-container-cli"
          devcontainer build --no-cache --image-name "${IMAGE_REPOSITORY}" .

          # Push image to GitHub Container Registry
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push "${IMAGE_REPOSITORY}"
