name: spotng
on:
  push:
    branches:
      - 'main'
    paths:
      - 'spotng/**/*'
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/spotng
          imageTag: dev
          subFolder: spotng/devel
          noCache: true
          push: always
  packcontainer:
    name: build pack image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack: [deb, rpm]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./spotng/pack
          file: ./spotng/pack/${{ matrix.pack }}.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/spotng:pack-${{ matrix.pack }}
